# Generated by Django 4.0.3 on 2023-04-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_alter_sale_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
